### ISSUE TITLE
USE valid AIO key

### ISSUE THREAD

**Issue by turnera2** [reef-pi/reef-pi#1027]
issue with telemtry 
entering AIO username and Key correctly.
error showing enter valid aio key

same issue with email indicating to enter valid password? 

pi 4 running raspian

**Comment by ranjib** [comment]
@turnera2 sorry for getting back so lately, my sincere apologies. Which version of reef-pi you are running?

**Comment by ranjib** [comment]
The adafruit.io setting section has poor UI components, that makes it harder to diagnose issues. Due to security reasons we don't show the passoword/token on the UI, even after its saved successfully (I'll be revisiting this). I just tested adafruit.io integration and it worked for me. Please reopen this issue if you are still encountering this without any workaround
