### ISSUE TITLE
horizontal line on PH graphs and ability to zoom into the PH graph.

### ISSUE THREAD

**Issue by gminton86** [reef-pi/reef-pi#1045]
Can we get an option to zoom in on the PH graphs that has definable high and low cutoff levels for the graph. and maybe a horizontal line on the cursor just like the vertical one to help visually see if the levels have climbed or lowered. 
![Capture4](https://user-images.githubusercontent.com/22088453/74092827-7f087800-4a97-11ea-9782-7c4294506c8d.JPG)

**Comment by ranjib** [comment]
@gminton86 the graphing capability in reef-pi is minimal. And i intend to keep it in that way, unless we get some contribution. This is primarily due to resource constrain. The prometheus/grafana integration is there for all advance use cases, including the one you described. 
Im closing this since I am not planning to work on this. My sincere apologies for the delay. Please feel free to reopen this if you want to discuss. We do plan to provide some customization (chart and colors).. but not definite plan yet
