### ISSUE TITLE
Is there a way to change how long it takes when I turn something off thats on a timer to turn back on automatically.

### ISSUE THREAD

**Issue by gminton86** [reef-pi/reef-pi#1078]

**Comment by ranjib** [comment]
@gminton86 help me understand correctly with an example. Currently equipment state will change immediately if you control them via the equipment tab. Times allow a fixed interval (in seconds) after which equipment can change their state back.

**Comment by gminton86** [comment]
If I have a light on a timer and its supposed to be on from 10AM to 10PM and its 2PM and I go to equipment tab and try to turn the light off while the timer is active it will automatically turn the light back on after say 10 seconds is there any way for me to change that time that it takes to turn it back to on .

**Comment by ranjib** [comment]
@gminton86 the auto-manual button on the top of light allows  you to manually set the intensity. This or a macro (that disable the light and switch on/off the relevant equipment are your best bet. Im closing this since I am not taking any work items from this. If macro or light manual/auto button is not working, let us know.
