### ISSUE TITLE
Add support for random, sine and lunar profile configuration via the UI

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#1089]

**Comment by inktomi** [comment]
Will this also allow for seasonal day length changes?

**Comment by inktomi** [comment]
One thing that is majorly missing from the apex lunar simulator is a way to calibrate the maximum brightness. It would be amazing if we could do this on the reefpi. Commercial moonlights are usually ran _way to brightly_.

**Comment by Ranthalion** [comment]
> One thing that is majorly missing from the apex lunar simulator is a way to calibrate the maximum brightness. It would be amazing if we could do this on the reefpi. Commercial moonlights are usually ran _way to brightly_.

This issue does not include any functionality to change day length times or calibrate maximum brightness, however I don't understand what it would mean to calibrate maximum brightness.  It seems like that would be handled by specifying the explicit brightness levels for each profile.

**Comment by ranjib** [comment]
Brightness calibration like feature should be achievable by the existing min/max settings for individual channels. When present reef-pi computes intensity value in accordance to that range. By default it sets to 0-100.

**Comment by ranjib** [comment]
Lunar cycle changes peak intensity (sine curve) at 30 days cycle, to simulate new moon and full moon.

**Comment by inktomi** [comment]
The issue is that max brightness is often way brighter than it should be. I did a video about this (and there's a paper linked with more detail) but as long as there is a way to set what brightness "100%" is, then the rest should fall in line. 

We need to be able to calibrate moonlights for the "full moon" brightness. Whether that's in the min/max settings or in a lunar cycle configuration doesn't matter much - I just wanted to make sure this wasn't overlooked since 100% brightness is just waaaaaaaay brighter than it should be. 

https://www.youtube.com/watch?v=dLyQB27knJE

**Comment by ranjib** [comment]
@inktomi I think we are covered here for the reasons mentioned above. Lets discuss if this is not the case in separate thread. This is not a lunar profile specific issue, its a general requirement to limit the min and max thresholds (minimum value for avoiding flickering and maximum for avoid cooking things up). We just have to do a good job in keeping this tested. I think once individual profile are tested in the beginning, we should be safe.

**Comment by inktomi** [comment]
I totally agree. I just wanted to make sure there was some awareness, as this is something that I can see being easy to account for up front but which could take a lot of refactoring if the overall system doesn't allow for it at some point in the future. Thank you!
