### ISSUE TITLE
[Request] "Clear Graph Data" Button

### ISSUE THREAD

**Issue by spaelectronics** [reef-pi/reef-pi#1103]
I think it would be nice to add a button to clear the graphs in reef-pi.

Currently, the only way to clear graphs is to delete the related equipment, and then re-add it.
However, by doing this, you end up loosing all calibration data.

I think having a button to delete graph data would be nice!

**Comment by JimmyKer** [comment]
Bump!

- [x] This is also a feature that is on my wish list.

**Comment by ranjib** [comment]
Hi Folks, 
I am acknowledging this issue. But unfortunately due to the current work queue priority I will not be able to work on this. But i want share a few related things that will make this problem smaller and also provide an universal workaround, albeit with not the most user friendly manner (UI)
Spurious and out of range data in reef-pi component appear mostly from few known issues. e.g. ph probes before calibration, erratic temperature probe etc. In 3.5 we have incorporated temperature sensor reading improvement that will reject bad data thus those cases are unlikely to happen again due to temp sensors. We plan to support moving average in addition sometime in future.
the reef-pi db command is a general purpose tool to update/delete/add data in reef-pi that are not possible via API/UI. This can be easily used to delete partial or complete usage data , as well as selectively fix a set of values. I'll be adding documentation on how to use this to address this exact issue: https://github.com/reef-pi/website/issues/85

Sorry for not prioritizing this feature ask. If you think this is a more common problem (other known avenues to get this out of range data), please share, i'll be definitely considering developing a more polished /purpose built feature to address this issue.
