### ISSUE TITLE
Having constant temperature errors

### ISSUE THREAD

**Issue by gminton86** [reef-pi/reef-pi#1115]
Look at the graph it says 9999999 and I keep losing my calibration.
![9999999](https://user-images.githubusercontent.com/22088453/79645395-0e5b9700-817d-11ea-91bb-2603b0de99ea.JPG)

**Comment by ranjib** [comment]
This is a circuit induced issues. Its not prevalent, but we do encounter cases where this happens. I will not consider it as a bug, since this is not induced by software (the sensor is indeed sending a bogus values). We do want to introduce some windowing function to detect and discard such errornous value, but I'll treat it as enhancement instead

**Comment by ranjib** [comment]
Closing since we dont plan to work on anything related to this. In future, we may introduce window based smoothing or moving average to deal with such noisy cases, but thats a stretch goal and will be a generic capability for everything timeseries related.
