### ISSUE TITLE
[Request] Run Macro on Alert

### ISSUE THREAD

**Issue by spaelectronics** [reef-pi/reef-pi#1124]
I think it would be nice to have the ability to run a macro on Temperature Alert (and other alerts).

Say a piece of equipment fails (say a heater or chiller), and the temperature reaches the alert threshold, a macro can be run, for example to enable backup equipment, or do some other emergency protocol.

**Comment by ranjib** [comment]
Can this be done using a separate temperature controller but the same sensor configured with the target macro.

**Comment by spaelectronics** [comment]
It can be done that way for temperature sensors, but what about other sensors, such as ATO?

Say you have an ATO Sensor, and it turns on, but doesn't turn off.. so it triggers the "Alert".
When the alert is triggered, I would like to have some emergency routine that can be triggered when the "alert" is triggered.

Is this possible? if so, how?

**Comment by ranjib** [comment]
After a lot of thought , i was not able to come up with a sane solution to this. I could add support for executing a macro on alert, but associating it with a specific alert will be hard. We are working on several improvements on macro, and I felt its cleaner to hookup some emergency action (modeled via macro) with an additional secondary sensor. In absence of a clear solution im siding with the human intervention as current best approach. 

Im closing this since i dont intend to work on it. Please reopen it if you have some other ideas to bring up in this context.
Sorry for taking so much time to decide on this. I was hoping i would be able to come up with something concrete... but couldn't
