### ISSUE TITLE
HS300 Driver Error

### ISSUE THREAD

**Issue by spaelectronics** [reef-pi/reef-pi#1170]
When using the HS300 Driver, i set everything up properly, I added a Timer to turn on and off equipment plugged into the HS300.

It works fine at first, but after a couple of days it ends up failing.

When I manually turn on or off a outlet, I get the following error:
`{"error":"Failed to update. Error: can't update 15 - can't get output pin"} | HTTP 500`

It seems like I have to delete the driver, then re-add it everytime this happens.

**Comment by ranjib** [comment]
@spaelectronics  I think this error indicates that the hs300 driver is not loaded. Its a common issue when using network driver (like kasa) and restart pi. What happens is reef-pi starts before network is up, causing the driver load failures.. which is then exposed as pin not found. I have to do a better job indicating and dealing with it in code.

Meanwhile, you can edit the reef-pi unit file to instruct systems to start reef-pi after network is up. https://unix.stackexchange.com/questions/257888/systemd-wait-for-network-interface-to-be-up-before-running-service

This issue should also be resolved if you reload reef-pi without restarting the pi, from the UI. 

If its a persistent issue. that may indicate that the IP  or some other network issue is present and the driver is not loaded due to that.

**Comment by spaelectronics** [comment]
@ranjib can you provide simpler instructions on how to do this? My Linux skills are limited, and I want to make sure I do it correctly.

**Comment by NvrBst** [comment]
I just wanted to say I also encountered this. I use the **KP303 Kasa Power Strip** (it's like the HS300, but only 3 ports). The HS300 driver works just fine with the KP303 (and just shows pins 0,1,2 as active, as it should). So just letting you know the reef-pi HS300 driver works for the Kasa HS300 and Kasa KP303.

It would be nice if this hs300 is loaded more elegantly, after the network is found.
I'm running the reef-pi on a Raspberry Pi 4, with Wifi.
To solve this temporarily I just added a `ExecStartPre=/bin/sleep 30` to the _reef-pi.service_, and it works fine after restart. Even though the Pi4 restarts very quickly, network sometimes takes up to 30s, so I had to do a larger delay than I wanted. But yea works for now until a better fix is found.

I assume with will happen with everyone who uses a Kasa Driver on WIFI.
