### ISSUE TITLE
Get a '404 page not found' when going to the Camera tab

### ISSUE THREAD

**Issue by Julien-Molina** [reef-pi/reef-pi#1188]
![image](https://user-images.githubusercontent.com/8566695/86924771-316c6600-c130-11ea-977f-3e549619ac7a.png)

This page seems to call a page that doesn't exist. The page works properly but a call is made to an api that doesn't exist (or at least not in the documentation).

![image](https://user-images.githubusercontent.com/8566695/86925039-9a53de00-c130-11ea-82ed-53bd2d10ece3.png)

https://reef-pi.github.io/additional-documentation/api/

![image](https://user-images.githubusercontent.com/8566695/86925078-a6d83680-c130-11ea-83a3-8f262668d9dd.png)

1. Go to 'Camera tab'
2. See error

 - Device Pi3 + Pi camera
 - reef-pi version 2.4
 - Browser Opera & Microsoft Edge

**Comment by ranjib** [comment]
Hi @Julien-Molina , my sincere apologies for responding late. This is benign and expected during the initial setup of camera. It means no images are present. This should go away after the first photo is taken. Im closing this ticket since im not taking any work item from this. Please feel free to re-open if you want to discuss.
