### ISSUE TITLE
Ability in the macro tab to wait for a sensor to be triggered

### ISSUE THREAD

**Issue by chrispo1** [reef-pi/reef-pi#1213]
It would be nice if we could wait on a sensor to be triggered with a possible timeout in a macro.

This would mainly be for automatic water changes.

turn off ATO
start drain pump
wait for sensor 1
start fill pimp 
wait for sensor 2
turn on ATO

**Comment by gminton86** [comment]
Yep I like this also

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1215
Exposing direct access to sensor in macros will be significant changes and may lead to bugs/inconsistency, since its a higher-level abstraction (on top of controllers).  I am proposing Oneshot controllers, akin to systems one-shot unit files that will be useful in automating the above-mentioned scenarios, like filling/draining tank using a level sensor,

**Comment by Ranthalion** [comment]
Adding as a branstorming idea, or more of a long term architecture change - 
We should decouple/split the producers and consumers of the sensors.  The controllers could start a routine that monitors the sensor, but is not responsible for acting on the value.   Instead, it only emits the new reading. Any interested consumers can take whatever action they want as new values appear in that bus.
