### ISSUE TITLE
Temperature Heater/Cooler Scale on Dashboard goes to 86 although Celsius is chosen.

### ISSUE THREAD

**Issue by sandormaracsko** [reef-pi/reef-pi#1227]
The Temp Sensor Unit is chosen to be Celsius,
The Current Temp Scale is OK shows around 23-25 degrees Celsius, but the temp - Heater/Cooler Scales goes up to 86 (probably Farenheit) this way the historical value graph cannot really be seen.
I deleted one sensor, restarted the Pi, readded the sensor again still the same issue.
![Capture](https://user-images.githubusercontent.com/66968798/92009161-02453000-ed40-11ea-8e3f-a2424b5ddcef.JPG)
thank you.
(version 3.4)

**Comment by ranjib** [comment]
This is expected. When we change the unit, reef-pi does not rewrite the older values. You can  recreate the controller with celsius if you want the older values to go away. Theres is a way to update the older values using reef-pi db command and I dont think I'll have time  to implement this (rewriting older metrics) as first class feature. Closing this since I am not planning to work on it.
