### ISSUE TITLE
Terminology Update.

### ISSUE THREAD

**Issue by DeeEmm** [reef-pi/reef-pi#1239]
Somewhere in the massive (and informative) reef2reef discussion thread I noted that a terminology change was proposed as part of a move towards more generalised control descriptions. In the absence of a formal discussion thread I decided to create this feature request so that I could add my suggestions (and others could add theirs). 

My background is automation and controls and so I thought there may be some value in my suggestions. Of course, this is just my take on it for what its worth. It is by no means meant to be any kind of criticism, but these are just the things that jumped out at me on first glance.

After using the interface for a short time I have noted the following:

'**Equipment**' - Only specifically relates to outputs, so should be described as such. New proposal: 'Outputs'
'**ATO**' - Is able to be used for much more than just ATO control. I can see this particular function getting developed further as it has the basis of a very powerful control engine and makes the control very flexible. New Proposal: 'Triggers'.
'**Connectors**' - This section appears to just describe physical Inputs and Outputs (or I/O as it is more commonly known). New proposal: 'I/O Configuration' or 'I/O Config' or 'I/O Mapping'.
'**Telemetry**' - Telemetry used in the context of Adafruit I/O is okay, but with the inclusion of email reporting is incorrect. New proposal: 'Communications'. (Note the 'Address' Field on the 'Settings' tab might be more at home moved here.)

With the Outputs (Equipment) tab able to both report the status of and control the outputs, it would also seem logical to have a page that shows the Inputs. You could reuse the same format but instead of a switch have some other kind of indicator. For the analog values you can display the numerical value. This would enable users to view and test equipment and sensors. You could also have a similar display for the dashboard too.

/DM

**Comment by DeeEmm** [comment]
Just been taking a look at the 'lighting' tab. I guess that this could also apply to other DC controlled loads, not just lights.

so additionally...

'**Lighting**' - applies to all PWM / DC controlled loads. New proposal: 'PWM Control'

**Comment by ranjib** [comment]
we have this discussed in the dev channel. There are two set of things
- The proposed terminology is not better in general. It may sound more familiar if you look at from your background. For me (automation/software) this is not intuitive. PWM outputs are also output and not necessarily more intuitive for the general audience. I also thing the word "I/O" will be alien to lot of our users. Put another way, this is just another set of alternative to existing terms, and im not sure if they are significantly better than the existing ones
- Though these features can be expressed in more precise technical terms, we would prefer to stick to reefing specific terms. This is to enforce a better user experience for reef keepers. We are doing this deliverately to simplify ui/ux part of reef-pi, which I think is becoming more complicated than the backend itself. And i'll not be surprised if we rename some of the backend components to reflect their UX portfolio. Since we find the UX (user experience) part harder to model we force ourselves to think that reef-pi should make reef keeping easy and intuitive, but general automation possible, since most things are sensor and digital i/o under a control loop at the end. Put another way, if theres anything that is stemming from reef keeping specific UX, that makes it impossible to use reef-pi for general automation, we would definitely want to fix that. But we would not make reef-pi a generic purpose control system and then retrofit reef keeping UX on top of it. This is purely a scope /priority/focus thing. I want to revisit this in 5.0 version. I expect all reef keeping specific features to settle by then and do some significant changes if needed and address those aspects. i.e. design reef-pi more of a generic control system and implement a specific reef keeping UX on top of it.  Till then we'll use reef-pi heavily for irrigation control, hvac control, model railroading and bunch of other non reef keeping related automation and learn from it. These learning will feedeback the next generation of improvements/terminology.
- Last but not least, in general non-functional features like this will be less priority. I'll definitely prioritize naming changes if there are diversity/inclusion issues or some other aspects that we think critical from governance perspective (bad words etc.).

**Comment by DeeEmm** [comment]
I agree, the actual terms should be commonly used and familiar expressions, which may not be those that I have suggested. My suggestion was not that the terms should be changed for those that I provided as these are merely suggestions, but simply changed from those currently used. It is of course easy for me to change the terminology for my own installation in the language file.

What I have noted is that the terms currently used do not reflect the functions they describe which makes it hard to understand. Menus should group items by function which is what any GUI should seek to do. In terms of UX this is what makes a system intuitive; when a user can determine how to use the system by simply looking at it, without the need for documentation or assistance.

The 'ATO' menu is a perfect example. I would expect this to **only** refer to 'Automatic Top Up' as it is a very specifically named menu. But instead this is actually a function group that is used to control a multiple non-ATO items. Of course it is fine that the ATO function can be hacked to perform other tasks, but when such hacks are prescribed as a normal method by which to control other items, then the hack becomes the norm. This by its own virtue suggests that it is incorrectly named.

It is also standard that in any GUI, the highest order of control description should be used in preference to lower order sub systems. I.e the top menus describe higher order controls, sub menus describe lower order sub systems. This hierarchy is the natural order of all things and following these rules ensures people can intuitively adopt and interact.

For example. ATO is actually a sub system, not a method of control. Describing a top level control method as ATO is very confusing and misleading.

I also disagree with your description of I/O. This is not just particular to my profession. The terminology is also adopted by the Raspberry Pi Foundation who's controller you have adopted: **GPIO** stands for **G**eneral **P**urpose **I**nputs and **O**utputs. Anyone who undertakes this project will instantly know what the term I/O means. I would venture as far as suggesting that describing the inputs and outputs as 'connectors' is actually misleading and _more_ confusing, as well as not following standard Rpi nomenclature. This directly affects how intuitive the on-boarding process is to those undertaking the project. Standardisation of terminology is very important. In the case of I/O the terminology has already been standardised by Rpi and should ideally be adopted as-is without modification to ensure continuity with established norms.

Of course, these are just observations from someone who has designed GUIs for many different applications for many different industries. There really is no right or wrong way to do it, but there are rules on how control hierarchy should be described and implemented, both in terms of function and interaction. This is the difference between a good UI and a bad one, an intuitive UI and a system that has to be learned.

I love the Reef-pi project, and now that I know how it works it's fine, because as a human I am able to adapt and overcome. However those initial few hours when I was trying to work everything out I found the interface to be confusing and not really self explanatory, especially in regards to how how to set up the I/O. It was definitely not intuitive. This confusion also lasted longer when trying to figure out how to undertake more complex control tasks. What I expected to find under the macro menu was actually under the ATO menu. Very confusing.

Again 'Macro' is a standard term. Specifically in the context of most peoples exposure to it - via Word and Excel. In both of these cases 'Macro' describes a complex control method using VBA.  My expectation, and the conclusion that I was intuitively drawn towards was that I should have been able to program the complex control method I wanted to achieve on the Macro page. Whereas Macro in this case is a simpler control method implementation and the complex task I wanted to achieve needed to be programmed on the ATO page.  Surely you can see how confusing this is to a first time user.

So again, it is not incorrect, but it is misuse of an expression in common parlance which forms a barrier to an intuitive interface.

All of this together means that Reef-Pi needs to be 'learned', rather than being 'intuitive'. The biggest barriers to the intuitive interface will also be those most commonly asked questions in the forums. You will already have a good idea on this. Just like I had to ask how to program a more complex control task, I expect many others have asked similar questions... How do I get it to do...X.Y or Z. Use this data to identify what is working and what isn't. What needs to be changed and renamed.

I appreciate that this is a really low order task. I created this post to share my 'first blush' with Reef-pi. You only get one first impression, and this first impression is an important one, especially from a GUI / UX point of view. I would want people to share their first blush on my projects with me too as it is an important insight into what works and what doesn't. Large companies spend a lot of money engaging user groups to give this kind of info. So it is by no means meant to be a criticism, only simply constructive comment. A first time users experience in using Reef-Pi. An experience that you can never have.

I truly hope you find this information of use and not as some kind of criticism.

/DM

Some thoughts...

- Geeks don't make good UI designers, their brains work differently to normal folk. 
- GUI change is always hard to implement on an existing system as the end users will always push back ("I preferred X to Y")
- Change in general is even harder to instigate when it is your work being changed (don't take it personally and don't push back)
- Existing users will 're-learn' the interface. They can easily adapt. No one will drop the project because of terminology
- Ask the community, but don't steer them. Final terminology wording can be put out to a public vote but it should still follow the rules of hierarchy.

**Comment by midweste** [comment]
I definitely see where both of you are coming from.  In order to make this project something that a reef keeper chooses to undertake, it important to keep things named in a manner that they understand.  I think its a great idea to have a general control interface and then use specific UI layered on top.  Awesome!

I'm using https://www.robo-tank.ca/ to run reefpi.  Rob (creator of robotank) did a good job of of labeling all his outputs and inputs, but they didn't really correspond to anything that was in the interface. However, to DeeEmm's point, I had a hard time understanding what the difference between Outlets and Jacks were.  I still don't know tbh.

Isnt' everything Equipment?  Lights, ATO, Dosing Pumps?

I almost feel that all equipment should be specified as part of the connectors configuration, and the top level menu items function as filters based on the type of item you configure the Inlet or Outlet as.  For example, I create the first outlet as a DC port to pin 15, then "add equipment" to that port.  This would give me an overview of each pin set and what I have connected to it.  

Take my comments with a grain of salt however.  I'm a developer by trade but have little understanding of the pi.

Just a couple days into using reef-pi and really liking it.  Thanks for all the effort by those involved!

**Comment by ranjib** [comment]
Everything is not an equipment in reef-pi world. We use that term specifically for things that are connected via outlet  and can have on/off state control ( commonly used for relay AC120/240). Equipment(outlet) and PWM (jacks) are two distinct type of outputs reef-pi provides. Equipment - connector separation exist to model the cases where you can have outlet/inlet without necessarily anything attached to them.

Im closing this issue since i am not taking any action item based on this. I have updated some of the docs and continue to do so and will try to incorporate some of the suggestion given here. It will be super duper awesome if you file specific issues r specific document/ui element term change , that will be easier to triage or act up.

Thank you so much for your valuable time and thoughts. Please feel free to re-open this issue if needed,

**Comment by DeeEmm** [comment]
Stonewalled.

**Comment by ranjib** [comment]
@DeeEmm i have not dis-regarded the suggestions. These needs to be broken into pieces to act upon. Having them here also helps us tracking and not being lost. We'll always prioritize things due to resource constrain, that does not mean we are not open to improvement. Hope that makes sense.

**Comment by gminton86** [comment]
Coming from someone with with no coding experience I found the way it is setup to be somewhat intuitive. So I don't know why it would need to be changed.

**Comment by DeeEmm** [comment]
> [gminton86] ...So I don't know why it would need to be changed.

It was an invitation from the Devs in the main reef-pi thread. (see first post)

> [ranjib] i have not dis-regarded the suggestions.

However...

> [ranjib] Im closing this issue since i am not taking any action item based on this

@ranjib Please don't forget that you actually asked for input and opinions on this.

It really is of no consequence to me. This feature request was not to get the terminology changed to anything specific, but simply to serve as somewhere that the conversation about terminology could evolve. Trying to discuss such things on an 800+ page thread that serves as product support / general enquiries / troubleshooting / development is pretty ridiculous.
