### ISSUE TITLE
Gravity Analog Electrical Conductivity Meter Driver

### ISSUE THREAD

**Issue by chrispo1** [reef-pi/reef-pi#1244]
I would love to monitor salinity, and just saw these new low-cost kits at Robotshop, they also have ph.

https://www.dfrobot.com/product-1797.html

**Comment by ranjib** [comment]
We  do not have plan to have dedicated drivers for individual analog sensors, but we have a common analog to digital converter driver based on ADS115. This will allow you to hook up the above mentioned sensor any many other using similar mechanism. 

Im closing this since i am not taking any work items based on this. Feel free to reopen this issue if you want to discuss this further,
