### ISSUE TITLE
Tinygo - standalone components - controlled by reef-pi [future?] 

### ISSUE THREAD

**Issue by stvnmbr1** [reef-pi/reef-pi#1253]
**Is your feature request related to a problem? Please describe.**
I have always been tinkering around separate components, controlled & monitored by reef-pi (like mqtt)
rather than running reefpi on raspberry, run it on docker / server, imo less prone to failure than the sd card (had to replace mine twice already)
If reefpi would fail, components still work independently on reefpi code.
esp allows OTA updates, so updating to new code can be done easily

https://github.com/tinygo-org/tinygo

**Describe the solution you'd like**
example - dosing pumps
ESP replaces raspberry pi
ESP runs the doser code in Tinygo (still in development but have a lot of drivers already)
ESP is connected to wifi, added as a driver in reefpi
Reef-pi controls the settings and syncs these to ESP

example - tds meter far away from tank
I've seen development on tds, looks great !
same idea, esp runs code to read tds
reefpi is connected to esp and reads out tds
cost is less because you don't need a raspberry pi and you don't need to setup a separate reef-pi for the unit.

I think, as all components are seperatly coded in reef-pi, the current doser code can be used on the ESP

**Additional context**
This is not a real request, more to see what your idea is about independent components and tinygo.
Just stumbled upon tinygo and looks promising for these use cases, could be worth taking a look at it.
They don't support PWM, yet, but GPIO, UART and SPI can be used. ESP support was added in september so i'm hoping development will go fast or the other ones.

you could have a reefpi dosing pump with buttons to do calibration or such and info display even, as a separate product, designed to work with reef-pi. just spitballing

https://github.com/tinygo-org/tinygo
https://github.com/tinygo-org/drivers

https://tinygo.org/microcontrollers/esp32/
https://tinygo.org/microcontrollers/esp8266/

**Comment by JimmyKer** [comment]
I don't know if this would help, but sharing doesn't hurt nobody ...

The maker off Jayfish (http://www.piworx.net/index.php/software-preview/) 
Is also moving from Raspberry Pi to ESP with the Octavia Project.
[http://www.piworx.net/index.php/beta-testing-is-here/](url)

**Comment by stvnmbr1** [comment]
@JimmyKer 
never seen this one before. I wouldn't run the complete reef pi on ESP, rather the specific components code.
But still have the option to monitor and control through reef pi.

**Comment by stvnmbr1** [comment]
ESPeasy is also an option for some components?
you can send commands through http and read out status json.

my leds run on ldd-h and an esp running ESPeasy, controller by a python script that sets pwm values.

**Comment by ranjib** [comment]
There are a few different things going on in this ticket, let me enlist the ones I can decipher as independent thing, and answer accordingly
- Im open to reef-pi as a separate controller and have esp32 or other micro controller based dedicate unit that does the actual measurement or monitoring. Kasa plugs work very similar. reef-pi's HAL layer, that interfaces hardware is not bound by physical limitations, one case have radio or wifi based devices integrated. We have to think about the control logic, in case that too is offloaded on the device.
- Tinygo is a good thing for running go on embedded device, but its orthogonal to what we are saying. Due to HAL layer, it does not matter what the microcontroller/esp32 based unit is written on (I personally will prefer C or circuit python over tiny go). reef-pi driver code is only aware of the wifi/radio protocol. Since this is not expected to be done under reef-pi codebase, I don't see us influencing that decision
- reef-pi will never run on esp32 or any microcontroller. It is aimed to be the most affordable complete controller, which means UI/webserver and bunch of other things. raspberry pi's full blown linux userland and the computing power is very useful in that way. I do intend to also build and share the docker images, that could be run on x86 as well for various other use case (including reefing, if appropriate). Im in process of rolling out my k8s cluster. After that. i intend to migrate my home, garden etc reef-pi controller on k8s, since most of it is wifi based drivers.

-  I personally have no plans for OTA style updates. Unless there's vendor/commercial interest I don't see what any other builder would like to contribute.  It will be nice to have reef-pi in standard raspberry pi distributions though. I'll plan to investigate that in future.
Im closing this since I am not talking any action items from this. Please feel free to reopen if you want to discuss further

**Comment by stvnmbr1** [comment]
- glad to hear, i know my explanations aren't always the best, but i try :) I would try to offload the control logic form eg a doser, so it works independent, but params configured by reef-pi. I will look into the drivers bit of the kasa plugs and others to see how this works in reef-pi. I could start with something simple the just passes measurements from sensors

- Ok, still have a steep learning curve, so tiny go doesn't really matter in this case. I thought it could be usefull for less coding.

- I never intended to run reef-pi on esp, raspberry or docker gives you more freedom as it's a linux OS. I've used the docker images before for the mqtt telemetry, that's the point i started thinking about esp driven components. I did some quick searches for kubernetes, i've never used it before but I understand the concept. There are a lot of repos available to connect an esp's measurements to kubernetes. I'll have to do some more research into this :)

- most stuff i used on ESP always had OTA, tthis would be a nice to have. but the code on esp shouldn't change much after all.


i'll keep this closed for now, reopen when i got more info/work done.

As always, thanks for your time to respond and think about this, you rock !

**Comment by stvnmbr1** [comment]
https://github.com/stvnmbr1/drivers/tree/master/tasmota

i've started a fork to try some things out. 
I flashed a wemos D1 with tasmota, ez web GUI and setup, http and MQTT capabilities


This setup would give you 5 channel led pwm control (needed in my case), 1 floater switch with relay control and 1 ds18b20 with relay control.  led pwms can be swapped with pca9685 for extra pwm outputs if needed (still need to test it out but i have a spare laying around).
I think this covers the basics of a standard reeftank. ato, temp control and light control.

I've added some testdata jsons, looks similar approach as the HS plugs. all info can be gathered by reading json responses. "http://tasmotaip/cm?cmnd=Status 0"  or relevant numbers to get specific info.
Relay/switches can be controlled by http request "http://tasmotaip/cm?cmnd=Power1 On-Off" or "http://tasmotaip/cm?cmnd=Power1 0-1"
PWM can be controlled by http request "http://tasmotaip/cm?cmnd=Channel1 0-100"
This looks very similar to controlling the relay in the HS plugs if i read the scripts correctly.

I'm thinking of starting a separate issue for tasmota integration - linking to this issue as main thread for separate compontents.
In a later stage i'm still thinking about MQTT as, if I understand correctly in the tasmota docs, the PCA9685 is only controlled by console or MQTT. 

What do you think about adding tasmota as a driver as this very flexible to control relays and switches and read sensor data? 

I have my second fragtank maturing and leds and sensors are expected to arrive soon for testing.
This could also help with TDS readouts for me, as this is a very minimal and cheap build to read out my rodi that is 6m away from my tank. And any other sensors ofcourse :)

**Comment by stvnmbr1** [comment]
#1273
