### ISSUE TITLE
[Request Add driver for  KASA HS100 plugs 

### ISSUE THREAD

**Issue by 2ftReef** [reef-pi/reef-pi#1255]
I have a strange problem. 
I have a raspberry pi 2 running reef-pi 3.5. I have a temperature sensor and an optical sensor connected. 
I recently connected TPlink Kasa HS100 plugs and used the HS110 driver to load it in reef pi.

But when I configure reef pi to turn on/off via a sensor it only turns on not off.

E.G. For the ATO it turns on the ATO pump plug when the sensor is out of water and turns off the plug on reef-pi to off when it touches water. but if I physically check the plug it doesn't turn off the plug. and if I try to turn the plug off on the kasa app it turns off and then turn back on after 5 seconds.

Driver support for the Kasa HS100 plug.

I have tried using the HS103 and Hs110 as well as using macros to control the action that reef pi must perform but with no success.

**Comment by ranjib** [comment]
I do not have kasa hs100 unit to test with, it will be hard for me to address, I'll keep this open in case I do end up buying one or some one else contributes the driver/plans to work on it. Do you see any error in the log. Does the hs100 plug on /off as expected from the equipment tab? If it works in that mode, we should close this since driver is not an issue.

For the macro thing lets track this in separate ticket. Please provide details of your setup.

**Comment by 2ftReef** [comment]
Issue has been resolved. I belive its related to my ATO config checking the sensor every two seconds that was causing issues. I have disabled the ATO and tested the plus on just the temp sensor and it is working flawlessly 😊👌
