### ISSUE TITLE
{"error":"stats for id: 'x' not found"} | HTTP 404

### ISSUE THREAD

**Issue by JimmyKer** [reef-pi/reef-pi#1268]
**Describe the bug**
Error message: {"error":"stats for id: 'x' not found"} | HTTP 404

**To Reproduce**
1. This can only be reproduced when you are using dosing pumps.
1. Add your dosing pump to the dashboard.
2. Go to tab 'Dosing pumps'
3. Click on 'on/off' to disable the dosing pump.
4. Reload reef-pi uing the admin tab.
5. Refresh the dashboard, this will bring up the error message.

**Expected behavior**
Show the graph history in the dashboard, maybe with a annotation that the pump is disabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/24880770/98089078-8e7bec80-1e82-11eb-9a39-9ab50eba82ac.png)

**Desktop (please complete the following information):**
 - Device Pi Zero WH
 - reef-pi version 3.5
 - Browser Edge Chromium (desktop + ios)

**Comment by ranjib** [comment]
This is a benign issues. When disabled, the doser does not have any usage data , hence the charting function in the ui gets this 404 (not found ) response. You have to remove the doser graph when you disable chart if you want to avoid seeing this error.
Im closing this since im not taking any work items from this. Its a very common issue that confuse reef-pi users (stale dashboard leading to 404 errors). I 'll document this as part of 4.0 release and will try my best to see if we can change the dashboard error handling to give more suggestions to user (e.g. check if you have any component that is disabled etc.)
