### ISSUE TITLE
How to add key/value elements to reef-pi.db

### ISSUE THREAD

**Issue by prsws** [reef-pi/reef-pi#1270]
Hi:

I'm working on UI changes (e.g. temp charts, etc.) and need to add new items to the db. For example, to make the temp chart customizable (instead of 0-100) I want to add chartYminValue/chartYmaxValue elements. I already have them in the UI but their values are not stored in the db, even though I added them to temperature_schema.jsx. What else needs to be done to accomplish this? Thanks for the help.

Regards,

José

**Comment by ranjib** [comment]
Hi @prsws as mentioned in slack chat, reef-pi uses boltdb that allows us to keep arbitrary byte array as key value pairs . We use this mechanism to store json objects in buckets (atos, lights etc) with ID as key and json serialized representation as value. Which means there is not database migration like work (like rake db:migrate) , and anything can be added at will. We have to do the due diligence for version compatibility.

For your work, i;d recommend starting with a chart object that encapsulate all these details as an attribute to individual ato , temperature or ato struct (chef controller/modules/ato.go), once its there, that all we need to do in terms of schema rest should work just fine as far as database is concerned. I'll close this ticket since i have no action to take from. Lets continue the discussion in slack
