### ISSUE TITLE
[Request] Sorting equipment display

### ISSUE THREAD

**Issue by 5ft24dave** [reef-pi/reef-pi#1321]
With monitoring of the equipment on/off, the order they appear seems to be random.

Is there a way to either sort by specific (numerically or alphabetically), or to drag items to the position wanted and save them.

![rp_equip](https://user-images.githubusercontent.com/37747536/103183274-18827900-4866-11eb-8460-c8bd21eeb19f.jpg)

**Comment by ranjib** [comment]
The order should reflect their creation order (chronologically). Right now there is no way to filter or do custom sorting/ordering. I do want to replace the current primitive chart with a better , more customizable widget. But this is not highon priority, so stay tuned.

 I am thinking of introducing a notion of groups or tags. That can be used for filtering a subset of equipment.

**Comment by prsws** [comment]
I submitted a PR a few days ago (which was accepted and merged into master) that sorts all of the lists (equipment, temp, etc.) alphanumerically by name instead of chronologically (by id). Please wait until the next official release to get it but if you're in a hurry you can build your own binary from source.

**Comment by ranjib** [comment]
Closing this since a new sorting mechanism is now incorporated into the UI code
