### ISSUE TITLE
Changes to suggeest to timers section

### ISSUE THREAD

**Issue by gminton86** [reef-pi/reef-pi#1336]
Can a timer that is newly made be able to put into operation immediately and function properly? The timer if made while in the middle of the timers schedule will not start till the next day properly. so if i make a timer from 10am to turn off at 10 pm it will not execute that timer till the next day. I would like it to be able to start when i make it and turn off at 10 pm then the next day it will turn on at the right time in the morning and off at night.

**Comment by gminton86** [comment]
Basically i would like to see timers simplified to just an on an off time in the same timer. not have to make 2 timers one to turn on and one to turn off.

**Comment by ranjib** [comment]
Timers trigger is based on schedule, it will be inconsistent design wise. You can create a macro and trigger it on demand, and then also use it with timer. For your specific case, I would not recommend a single timer to start 10AM and then revert back after 12 years. This will result in loss of state if the pi powercycles in between. Its best to split it up in two separate timers, one for on , and another for off. It reduces the risk and will allow you to check the 10 pm behavior. The revert back feature is intended for smaller duration , there is no code issue for long duration revert back action, its just risky and can be inconvenient for the reasons you and I shared. Im closing this since I don't intend to make any code changes (bug or features). Feel free to reopen if you feel strongly, and we can discuss further
