### ISSUE TITLE
Kasa HS300 | Polling for status

### ISSUE THREAD

**Issue by woejillis** [reef-pi/reef-pi#1339]
I have 2 Kasa HS300 wifi power strips that are integrated into Smartthings and have also been added to reef-pi. 

The plug status (on/off) doesn't update in reef-pi if I use Kasa or Smartthings to turn the plugs on/off. It would be generally useful if the plug status could be polled from Kasa at regular intervals.

**Comment by NvrBst** [comment]
Hello. I agree with this 100%.  I love Reef-Pi. I use a Kasa Power Bar (3-socket version), and use the HS300 driver. The driver works fine, and can control the Kasa Power switching on and off.

However if you control the switch outside of Reef-Pi (i.e. turn the lights OFF directly), it will always appear as ON in reef-pi. Reef-pi never polls the current status of the switch. I know the python-kasa (or pyHS100 whatever python library you are using) libraries both can poll states.


For any Kasa devices found in reef-pi, the state should be polled (every 30s or 60s), to sync up the on/off status of the device, if they changed via external means.

**Comment by woejillis** [comment]
If possible, I would like the polling period to be a field that can be changed. For my application, something closer to 1-5 seconds would be desirable assuming my raspberry pi hardware didn't have an issue keeping up.

**Comment by NvrBst** [comment]
> If possible, I would like the polling period to be a field that can be changed. For my application, something closer to 1-5 seconds would be desirable assuming my raspberry pi hardware didn't have an issue keeping up.

Any polling update will be better than what we have now (no polling update). If he wants to make a field for custom polling that is fine as well. But I know that is a tricky bag to open.

Home-Assistant also used to allow custom polling for TP-LINK Kasa devices, but after a long discussion, they hardcoded the 30s poll into their system, and removed the `scan_interval` from the setup. Since to update, you need to repeatable poll the status, it's a more cumbersome process than the device pushing the update status, and the API that Kasa devices (and python-kasa library) use were not meant to be hammered every 1s or 2s (~3500 times an hour per device). In the end too many users were doing it, so they removed that ability.

10s may be more reasonable for the kasa devices, but I know a lot of people in the forums were even against 10s polling. In the end 30s was set, and to get lower polling you have to do a weird workaround.

That's HASS, and not reef-pi, so I dunno the decisions reef-pi would make. But I assume it'll not allow 1-5s polling updates (for fear of undefined behaviour). I would be expecting 10s-30s range. And am fine with the interval being hardcoded for now.

**Comment by woejillis** [comment]
What you state makes perfect sense in that context. Any polling is better than nothing!

What I'm battling now is that my automation lies outside of reef-pi. If the Kasa outlet is ON but reef-pi thinks it's off, upon a restart it will turn the outlet OFF. 

I'm not sure if this is normal behavior or since Reef-Pi thinks the outlet is off, upon restart it forces it off. Even if it polls every 30 seconds, it should recognize before a restart that the outlet is ON and hopefully would not try to turn it OFF upon startup.

**Comment by ranjib** [comment]
I am planning to make the startup behavior, where reef-pi syncs equipment, configurable. 
We can have this polling behavior configurable in kasa driver, if anyone interested in working this. Thanks to HAL and the UI scaffolding, this should not be complicated.

**Comment by woejillis** [comment]
That would be great!

**Comment by ranjib** [comment]
stay off on boot is now configurable per equipment in reef-pi. 
i do not have any plan to work on the polling feature (status sync), hence closing this ticket. If any one plans to work on it, let me know happy to walk through the process
