### ISSUE TITLE
Feature Request: graph any analog input and alert if out of range

### ISSUE THREAD

**Issue by JohnRudolfLewis** [reef-pi/reef-pi#1415]
I have a whilelabs tentacle t3 with ph, temperature, and conductivity modules.

I would like to graph the conductivity from the ezo-ec (after doing math to convert to salinity)
I would also like to be able to alert when it is out of range

One general solution that would satisfy me, is I could use file-analog driver to read a file that I am responsible for writing with my own code. reef-pi would be responsible for graphing the value on the dashboard and alerting when out of range. This would extend to any analog input anyone cares to use.

**Comment by ranjib** [comment]
I intend to convert the ph module into a general purpose analog module. Currentlly you can do whatever you mention using the standard ph module, except it will have little poor aesthetics due to it being inside pH module. But unit, calibration, driver , control mechanism .. all should work. I use the ph module for current monitoring etc.
