### ISSUE TITLE
Admin->Reload is not working

### ISSUE THREAD

**Issue by prsws** [reef-pi/reef-pi#1447]
Hi:

Tested versions 3.5, 4.0 & 4.1 and all respond the same:

![image](https://user-images.githubusercontent.com/4139202/117492200-4461e980-af3f-11eb-8206-8a934392e828.png)

Further tests point to problem is at the API level and not an UI issue:

![image](https://user-images.githubusercontent.com/4139202/117492409-8e4acf80-af3f-11eb-8f1c-6512a369f755.png)

Code looks very similar to Admin->Reboot but reboot works fine.

Thank you for your help.

**Comment by ranjib** [comment]
This is expected right now. Its not  pleasant, but this is not a feature bug, as in the reload works, its just that during the relod time server is not present hence UI can temporarily errors out. But since the UI polls every 10s , it should come back just fine. Im closing this as I do not have any action to take . Please reopen this if you want to work on improving the UX
