### ISSUE TITLE
MQTT QoS value not working

### ISSUE THREAD

**Issue by mmarekd1** [reef-pi/reef-pi#1470]
It seems that the only way you will receive messages is when the QoS value is either 0, 1 or 2. I had my set to 3 which is typical MQTT value used for exact but there are no messages flowing if set to 3.

**Comment by ranjib** [comment]
reef-pi uses eclipse [paho mqtt ](https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang)library underneath
https://github.com/reef-pi/reef-pi/blob/master/controller/telemetry/mqtt.go#L57
We'll have to first understand if this is due to reef-pi converting the qos from int to byte or its not supported by the paho library itself

**Comment by ranjib** [comment]
hi, please let us know if you are still interested in triaging this , otherwise we'll close this due to inactivity

**Comment by mmarekd1** [comment]
Hello,

 

Sure more than happy to do it.  Let me know what works for you.

**Comment by ranjib** [comment]
It looks like paho (the library reef-pi is using ) only access 0/1/2 as qos value: https://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/qos.html

**Comment by ranjib** [comment]
Digging further, it does look like qos values should only range from 0-2. 3 is not a valid value: https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/

**Comment by mmarekd1** [comment]
Ranjib,

 

Thanks for the info.  I guess there are inconsistencies in numbering between different deployments.  Some number from 1 through 3 and others 0 through 2. Unless this is explicitly documented that Reef-Pi perhaps the selection should be restricted from 0 to 2 as opposed to completely open.  The up and down arrows allow any number at present.  I think this will be most effective and easiest fix.

 

While back I’ve exchange some notes on the forum on the separation of the MQTT messages from different Reef-Pi’s.  Are you planning to resolve this as well while you are focusing on the MQTT ?  If you need some additional examples please let me know I would be more than happy to provide.

 

BTW Excellent work on the Reef-Pi!!!!!!

 

Best Regards

Mark

**Comment by ranjib** [comment]
@mmarekd1 i would definitely like to resolve the topic based publishing issue. I am unsure about documenting the qos values though. My initial research (paho mqtt implementation and mqtt 3.1/5.0 specification) indicates that 0,1 and 2 are the legitimate qos value. 
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html

I'm closing this since I am not taking any action item from this. Feel free to reopen this if you want to discuss further. We can track the "publish mqtt messages on a specific topic" as a separate issue.
