### ISSUE TITLE
Switching to Create React App and TypeScript

### ISSUE THREAD

**Issue by Wraul** [reef-pi/reef-pi#1529]
Hi

I'm interested in doing a bit of work on reef-pi.
To start I'm planing on doing a bit of cleanup and upgrades of the frontend dependencies.

After that I would like to try to convert the frontend build system to using [Create React App](https://create-react-app.dev) which is the "official" way of building React Apps.

When the app builds using Create React App it should be quite easy to start a migration to TypeScript. TypeScript should help us greatly in avoiding runtime errors in the frontend.

I believe these changes should be of great use for the future development of reef-pi.

This issue is mostly to ask if these changes would be of interest and if any related pull requests would be accepted?

**Comment by ranjib** [comment]
Typescript is definitely a better choice, but its effectiveness for reef-pi at this time is limited. This is due to test coverage and the migration cost.  Create react app will always showcase the latest and greatest, and reef-pi likey to lag behind, but this does not mean it can benefit from the latest. Unless there are specific gaps in reef-pi (like we are seeing lots of runtime errors) I'll be reluctant to back a type script migration as first improvement.

We have a number of front end specific gaps, including charting, responsive components and design consistency that are of higher priority. I'lll recommend starting with those and then incrementally switch to type script if it makes sense.

**Comment by Wraul** [comment]
I see. Sounds resonable.

I will start by making a much smaller pass to the dependencies and frontend build. Remove a couple of unused or unnecessary dependencies and performing a couple of upgrades. I should have a pull request for that in a couple of days I guess.

After that I'll see if I can come up with some designs to get the GUI a bit more consistent and polished.
