### ISSUE TITLE
Reverse dosing

### ISSUE THREAD

**Issue by guestisp** [reef-pi/reef-pi#1602]
Please add reverse dosing option, like GHL does on their pumps.
Reversing a dose is useful to clean the hose and keep the product in the container (the container can then be areated, shaked with a magnetic stirrer and so on)

**Comment by ranjib** [comment]
This is already possible. Its not a ready made feature in the UI, since we reef-pi runs a variety of hardware setup, and this feature requires some special circuitry,
You can employ an l293d for dosing pump control, and control the direction by two outlets (that  in turn control the l293d direction pins). reef-pi allows all these and many similar fine controls, but those are not presented as first class UI components (due to the standard software;s requirement on running a very lean, generic hardware)

**Comment by ranjib** [comment]
closing due to incactivity. feel free to reopen if you want to discuss further
