### ISSUE TITLE
HTTPS Failed to run

### ISSUE THREAD

**Issue by coaxman** [reef-pi/reef-pi#1604]
I turned on HTTPS:// I did not set a port.   I had no issues after booting but had a power outage and when Reef-Pi rebooted I am getting an error:  Failed to start HTTPS server.   it's showing 0.0.0.0 with no port number.     I am pretty sure the port number is the issue but I can not open a config file.

**Comment by jonri** [comment]
I had a power outage a few days ago as well, and I've noticed that on fresh boot MQTT will not connect.  I suspect both of these issues might happen because Reef-Pi starts up before the network is connected and there is no mechanism to automatically retry.  Hitting the Reload button fixes it because it makes the program start up again while the network is already available.

**Comment by ranjib** [comment]
Use systemd direct (after=) to specify reef-pi should start after network, as described here: https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/
