### ISSUE TITLE
ATO feature discussion

### ISSUE THREAD

**Issue by schwabix-1311** [reef-pi/reef-pi#1696]
As I understand the source code currently ATO controller checks water level input every ATO.Period seconds no matter whether it is filling or not.
This means your period must be quite short WRT to the rate at wich the tank is filled. (The 120 sec suggested by UI seem inapropriate.)
This also means ATO usage is always a multiple of period.

Wouldn't it be more accurate, and for some (creative non-ATO) use cases more flexible to allow a long check period, then as soon as the controlled device is activated switch to a shorter period?

As a result one could check water level once a day, and nevertheless have fill volume recorded with e.g. seconds precision. All combos of a digital in and an out to equipment or macro would react more immediate.

All this would need is either two different periods configurable, or a bit simpler, use a fixed 1sec period while device is active. Pump turn off and thus water level, as well as usage date (= refilled volume) would be more accurate.
Whether there's a use case for the combination of short check period and long activation period I don't know ... basically it would allow to create hysteresis effects.

**Comment by ranjib** [comment]
This feature ask here is similar to https://github.com/reef-pi/reef-pi/issues/1246 
I think this can be done with the current integrations among timer , macro, and all other subsystems. It is however little bit complex. For the use case you have mentioned, a user can crate an oneshot ato that is configured to poll at 1 second interval and then trigger it once a day. 
I am not sure about the usage dashboard, I have to test it out to see how that plays out.

**Comment by JimmyKer** [comment]
Hi ranjib, 

I've tested this new approach on the last weeks, and this works perfect.
Also is the dashboard perfect updated.

I didn't need to create a new Timer to start theOneShot Timer, as a Timer was already implemented to make sure the ATO is never switched off, in the past I had it a couple times that the ATO was switched off (probably due to my fat fingers on a small phone screen 😊)

Thanks for the information!

Kind regards,
Jimmy

**Comment by JimmyKer** [comment]
I had 3 times in the last months that the ATO keeps running, luckily robo-tank has a float-switch that stops the ATO pump.

I believe this is the issue:
When the ATO triggers the 'alarm after xx seconds'.
Then I receive this error alarm message +40 times.
I've tested this now without a ATO pump attached.

Had someone else the same problem?

**Comment by JimmyKer** [comment]
**I think I've found the problem:**

When an ATO is switched **OFF**, and **triggered** by an **Timer**:
_**The failsafe to switch OFF the ATO doesn't work.**_


_I would expect that:_ when the ATO hits the alarm time-out and is set to switch off, this would stop the ATO from running.

Additional I get errors messages by mail when the alarm is triggered, but because the ATO doesn't shutdown the messages keeps coming every milli-second.

**Comment by ranjib** [comment]
@JimmyKer when ato is disabled it should switch off the ato pump. This is the reef-pi software logic, and i personally test/use this. In fact this is how i find out how my ato containers are running dry, by getting the alert email. I have also seen this working during skimmer overflow induced ato run over. So im sure there is something else involved , likely the timer specifics. Can you provide details on the ato configuration (check interval, disable on alert state and alert threshold).
Currently, the frequency of alert is same as ato check interval. we need some equivalent of hysteresis to deal with the too many alert issue. I would recommend setting that limit to 3 that way you'll only get 3 emails every hour.
