### ISSUE TITLE
Journal - date sorting

### ISSUE THREAD

**Issue by schwabix-1311** [reef-pi/reef-pi#1702]
Field timestamp of journal entries is preset with a date converted to string.
It can be edited, with surprising effects on sort order.
Below chart shows sample data where the value equals the day of month, thus a staight line should be shown. The x-axis shows the preset date for two, and slightly edited for three entries.
![Bildschirmfoto von 2021-12-28 20-35-27](https://user-images.githubusercontent.com/78373870/147601533-f1629e99-5fc9-484e-b077-14446f9b9dfc.png)
Besides the presets being sorted backwards, the other three are obviously not in any date order.

One solution could be to convert whatever the user enters into a real date object (or a normalized string representation), store this and display it using a conversion to user locale wherever this is exposed.
Same applies to all time axis on the various graphs.

**Comment by schwabix-1311** [comment]
I did one more test: added an entry with exact same date as an existing one (Tue Dec 7 2021), but used another weekday (Thu Dec 7 2021). Sorting is totally off. The resulting order is neither alphabetic, nor by date.
This means, when entering data late (since it was forgotten), you have to lookup the weekday to get proper sorting.

**Comment by aloonj** [comment]
Perhaps related, but when adding Journal graphs to Dashboard, the most recent value is on the left hand side, whereas for the temp and ph graphs, the most recent reading is on the right hand side. This makes it confusing when glancing at dashboard.

![c1925403-7217-4d11-bdd8-469359c9c058](https://user-images.githubusercontent.com/27914673/149657179-3fa71a0f-cd5d-484e-a26f-136fe738b00b.png)

**Comment by ErenKarapinar** [comment]
I do have the same problem right now, date sorting is random i guess can we fix this  ?
@ranjib

**Comment by ErenKarapinar** [comment]
hello @ranjib can anyone fix this?

**Comment by ErenKarapinar** [comment]
@ranjib hi

**Comment by ranjib** [comment]
Hi
I am aware of this . I have plans to address this , if requires some
changes in the stats bucket module. This was a poor user bug (sorting )
that I overlooked. I’ll get back to this , but its not part of 5.2, and
I’ll be busy with aquashella this month . Probably soon after that I’ll get
tp address this

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1784
this will be a painful fix. because of a mistake in type declaration from my side, i do not see a good way to fix this without impacting existing journal entries. Since we cant accept this issue as status quo, i have decided to do the right thing and update the original type to include time information, which will allow us to sort and chart the parameters properly. But this will also result in previous entries timestamp (being declared as string in the previous releases) not being detected. I recommend users to delete and recreate the parameter, re adding the entries if possible to new parametere.
sorry folks. but at least this issue is resolved now. and longer i wait more users will be impacted. i hope you all will understand.
