### ISSUE TITLE
MQTT to allow topic definitions

### ISSUE THREAD

**Issue by mmarekd1** [reef-pi/reef-pi#1733]
reef-pi does not allow to assign the MQTT messages so they are specific to reef-pi. Device name can not  be identified as separate topic when published to MQTT.

See for example how Tasmota devices handle the MQTT.  This would be an ideal presentation as it provides complete flexibility.

![mosq-Capture](https://user-images.githubusercontent.com/86674425/148286210-62388a4d-c010-4c69-b6e4-a540c7f7be65.JPG)
![mqtt JPG](https://user-images.githubusercontent.com/86674425/148286215-79f36253-49f4-4555-860c-7c64d6a3c50d.JPG)

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1734
Thank you for filing this. I think I understand now better. In mqtt this is done by adding a prefix with / . I was confused earlier since we already use the topic name, i.e. individual metrics are topic. What was not clear that if I just do "foo/bar" it will automatically translate into bar categorized under foo. I hope this solves the issue. reef-pi users will now be able to specify a prefix, and when present , reef-pi will honor it and emit individual mqtt message with the "prefix/" prepended.

**Comment by ranjib** [comment]
this will be released in the next version. Feel free to reopen this ticket if you want to discuss more.

**Comment by mmarekd1** [comment]
Thank you!!!Sent from my Bell Samsung device over Canada's largest network.
-------- Original message --------From: Ranjib Dey ***@***.***> Date: 2022-01-06  9:33 PM  (GMT-05:00) To: reef-pi/reef-pi ***@***.***> Cc: mmarekd1 ***@***.***>, Author ***@***.***> Subject: Re: [reef-pi/reef-pi] MQTT to allow topic definitions (Issue #1733) 
this will be released in the next version. Feel free to reopen this ticket if you want to discuss more.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/reef-pi/reef-pi/issues/1733#issuecomment-1007092445",
"url": "https://github.com/reef-pi/reef-pi/issues/1733#issuecomment-1007092445",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
