### ISSUE TITLE
Salinity Monitoring

### ISSUE THREAD

**Issue by scribblrsam** [reef-pi/reef-pi#1785]
Hi, 

Do you have any aspirations to add the ability to minitor salinity with a probe or is there a way to do this? If not can you advise roughly how the code base is set out, where would i have to look to add this functionality? I assume a new controller in go and some front end pages as a minimum? 

Thanks 

Sam

**Comment by ranjib** [comment]
You can already do salinity monitoring using the ezo-ph driver, because the underlying protocol is same. Add the ec ezo circuit as ph circuit in reef-pi and use the ph module to attach the analog input. I dont plan to add a new module in reef-pi as the underlying driver, control code, UI all reusable. It is because of this reason the unit in ph module is configurable (to accommodate any analog input).  Let me know if you are not able to do this, i can help you out with the setup

**Comment by TheRealFalseReality** [comment]
ok cool! I wanna check this out
