### ISSUE TITLE
Potential Power Loss Corruption Issue

### ISSUE THREAD

**Issue by ALPHAB3TS00P** [reef-pi/reef-pi#289]
I am running into an issue of when I lose power or unplug the pi zero w with reef-pi running (currently only an 8 channel relay and a temperature sensor is hooked up), once I regain power I am unable to SSH into my pi or view the reef-pi web service. also the relays go through a huge amount of clicking.... its using DHCP and when I try to ping it I get "Request timed out" and "Destination host unreachable" with 50% packet loss. 

I was in the middle of making a how-to video for the temperature sensor and had to stop because the pi is now unusable. I will need to format the card. I can wait and send you the image/boot drive if you think it will help.

**Comment by ranjib** [comment]
- Failure to ssh is probably due to the Pi having a different IP than before. If your home wifi router has a web dashboard (generally its accessible from the gateway IP , something like 10.0.0.1 or 192.168.1.0), you can use that to find out the IP of your pi, or configure the router give it a fixed reserved IP. This is not reef-pi specific, but something related to Pi & DHCP.
- The relay should go through a series of clicking depending upon its own state and how you had instructed reef-pi to what state they should be in. reef-pi will sync all outlets to its last known state (on or off) based on timer or on-demand action, so during that if the relay is in different state (say you have a normally open relay powering and equipment which you have turned on with reef-pi UI,  so upon reboot, reef-pi will change the relay state to reflect the last applied state). But this should not be a lot of clicking, should be same as the number of channel at max.

The lost IP is a common issue, that I have also encountered. i.e. by some reason if reef-pi lost internet connection, its kinda hard to find out what its new ip (since web ui does not work) , and it also means theres is no easy way to even shut it down (unplugging power will trigger a hard shutdown, which can potentially crash the sd card). I am working on getting a minimal physical interface support (a button and an LED display) to at least support graceful shutdown, and IP.

I can keep you posted on that, if you want. I am keeping this issue till you find a way to figure out your controller IP
https://www.youtube.com/watch?v=7M3zE2kRJZk

**Comment by ALPHAB3TS00P** [comment]
![image](https://user-images.githubusercontent.com/15350027/34809064-f011cee6-f64f-11e7-8518-01951182e987.png)

![image](https://user-images.githubusercontent.com/15350027/34809080-1378bdae-f650-11e7-97d6-4acbf6fda631.png)

![image](https://user-images.githubusercontent.com/15350027/34809110-31d2f04e-f650-11e7-953a-288fccb7d70e.png)


I might just have to format the SD card and start over. I cant find out how to access the machine (the pi 0 has the micro usb and I don't have any adapters on hand to actually go into the box. ) I like the idea of a push button and an lcd or led display to help out with this. 

Thoughts?

**Comment by ranjib** [comment]
You know, I dont think that the sd card is fried, if it was then it will not boot and get a dhcp address. It means network is up, and that can only happen if the linux system boots correct which means sd card is working as well. Is it possible to connect physical display (like hdmi+tv) to the pi for diagnosis? may be ssh is not enabled, .. but still it should respond to ping. Connecting it to a physical display and booting it is the definitive way to find out whats wrong.  I use a usb ttl cable as well, sometime when I dont want to move the pi and take it to attach with my TV.

**Comment by ranjib** [comment]
Format should be your last option, it is definitely an option, but if you can understand what went wrong, we can prevent it from happening again. I would also encourage configuring the router to give your controller fixed/static IP, if possible, once its up

**Comment by ranjib** [comment]
Closed by mistake :0/ , reverted

**Comment by ALPHAB3TS00P** [comment]
![image](https://user-images.githubusercontent.com/15350027/34858546-3e314ff2-f70e-11e7-8dd2-a8a9e8393ac0.png)

I hooked up a monitor to the pi and after a bit, it hung on the screen that is attached

**Comment by ranjib** [comment]
I think the sd card is fried or some data is corrupted, formatting is best course of action

**Comment by ALPHAB3TS00P** [comment]
Ya that is what I ended up doing
