### ISSUE TITLE
Improvements to dashboard lighting widget

### ISSUE THREAD

**Issue by Massild** [reef-pi/reef-pi#439]
In attempting to further understand the lighting algorithm used in Reef-Pi I found that the current widget does not provide any information not already in the lighting settings.  My suggestion is to add the following features.

1. It would be nice if one graph showed all channels instead of individual graphs per channel.  This would save space and allow a better visual of the light mix
2. The ability to set the graph display color to match the light color (color drop down per channel maybe?)
3. It would be nice if the lighting graph showed a rolling 24 hours by the minute of the actual output.  I am not sure if Reef-Pi logs this now but it would be great to see if there was a temporary change in the past perhaps.  

These are just suggestions from a grateful user of Reef-Pi

**Comment by ranjib** [comment]
- current light graphs has one graph per light and one line per channel, so, multiple channels are already presented inside a single graph, as long as they are defined inside same light.
- I think custom color for individual channels is a good idea. I am open top rename this ticket or create a new ticket to track that part, but I'll only be able to get to this after the current UI refactoring spree is finished
- The graphs actually showing how the rampup/ramp down happnes, its interpolated linearly and applied after every 30 seconds. But the data is not granular, i.e. if you roll over mouse it will only show 2 hour intervals. we can generate all the data points after every 30sencods, but that will slowdown the rendering and will not anything new (since the graph shape is same), except users will be able to see values after every 30 seconds when they mouseover. reef-pi logs the light values after every 30 seconds, for each channel (e.g. ```lighting-subsystem: Setting PWM value: 99  at channel: 3```)

Thank you for the feedback, really appreciate it

**Comment by Massild** [comment]
Thank you for the clarification.  I now understand the intent of the "jacks".  I have a light that has 3 inputs 2 of which are the same color (Royal Blue) and another that is White.  The way I configured it was to put both RB channels on one jack and a second jack on White.  Looking at the UI again I see that I should have all channels for a given fixture on the same jack and control the colors there.  

I will open a new ticket for the custom colors since that will be cleaner.  I completely understand it is UI and not functionality so it will come later in the design process. 

Thank you for the clarification on the graph as well.  I will close this ticket.
