### ISSUE TITLE
Adafruit.io AIO Key Not Saving

### ISSUE THREAD

**Issue by spamr** [reef-pi/reef-pi#451]
Upon entering my Adafruit.io username I receive the following message instantly "Please set a valid adafruit.io key" and after hitting "update" the key does not save. 

When reloading the page after saving the AIO key the textbox is null.

running 2.0.0-beta-6

**Comment by ranjib** [comment]
this is fixed in master, will be part of next release. Couple of notes:
- reef-pi UI will never show existing/set password & token. hence the adafruit.io token field is empty , thats not a bug. It does not mean reef-pi is not save the new token when user type it in the field and hit  save button. We'll add information text message in the UI to make this clear
- I have ensured 2.0 sensors (ph, temperature and ato) along with their usage (heater/cooler) are all integrated with adafruit.io based metric emission

Let us know if you have any concern,
