### ISSUE TITLE
Warn users when https is enabled and port is 80

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#625]
reef-pi allow users to configure api/UI address (host and port) as well http/https. Currently this allow users to specify port 80 (http) while https is enabled. When configured like this user will see the webpage being download instead of rendering it. The following screenshot shows port 443 is used without https being enabled. 
<img width="1208" alt="screen shot 2018-10-28 at 8 13 02 am" src="https://user-images.githubusercontent.com/316306/47617883-80bc5100-da89-11e8-8dc0-540e17f91dec.png">

As a mitigation measure, lets implement warning message in configuration UI (validation?) when user specifies port thats not 80 for http , and port 443 for https.

**Comment by Ranthalion** [comment]
Is the intention to explicitly prevent the following cases?
 - Prevent http with port 443
 - Prevent https with port 80

Validation is a good choice if this is considered invalid.  If we want to allow to user to save with these values, then we'll need a new UX pattern for warnings that can be ignored.  

In this case, I don't think we should allow the user to save with these settings (mainly because it makes troubleshooting much more difficult).

**Comment by Ranthalion** [comment]
I'm not against showing a warning.  Here's another idea.
Move the Use Https field into the address field where the protocol would appear.  By default, we can leave off the port and default it to the appropriate value based on the user selection.  If the user adds a port to the address, then we use that instead of defaulting based on the protocol selection.

![image](https://user-images.githubusercontent.com/1632746/47686297-c7589b00-dbb0-11e8-958d-f2057c108781.png)

I would imagine that most users don't intend to change ports, but http/https is more understood.

**Comment by ranjib** [comment]
@Ranthalion you plan to work on this? If not lets close it
