### ISSUE TITLE
Allow controlling smart outlets via reef-pi

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#642]
There are many off the shelf smart outlet available in the market. It would be nice if reef-pi can control some or at atleast one of them. Building controller with outlets/AC sockets is painful, for north american users ADJ powerstrip solve some of this. Having support for a smart outlet thats available for everyone can significantly reduce the risk of building power outlets.
More here: https://www.reef2reef.com/threads/reef-pi-an-opensource-reef-tank-controller-based-on-raspberry-pi.289256/page-309#post-5122235

**Comment by theatrus** [comment]
Also of note would be SNMP or Ethernet controllable units, e.g. https://www.amazon.com/CyberPower-PDU15M10AT-Metered-100-120V-Rackmount/dp/B00NEHUX08/

**Comment by robertobuti** [comment]
I suggest use RS485 relays board, so plugs number ca be increased as need. RS485 interface if provided in reef-pi daughter board , easy to manage and connect, reduce number of wires. Searching with google there are many realy board, some of them boxed. (not with socket unfortunatly) but still cheaper solution.

**Comment by theatrus** [comment]
@robertobuti Do you use the MiniUART or the full UART? Do you use the RS485 direction control or is it write only?

**Comment by robertobuti** [comment]
ciao @theatrus , i don't know what you means with "miniUART", but i have used the classic circuit driver where DE is driver by TX (inverted), is not perfect RS485 circuit, i agree.... but is common method to use RS485 without addittional gpio for direction. Still bidirectional, half duplex obviously.

**Comment by dmolavi** [comment]
Discussed in forums and on slack..I vote for Digital Loggers Web pro switch support. No cloud needed, all local control via network.

**Comment by philkry** [comment]
i started building this project but also rely on a smart plug since the ADJ powerstrip is not available in Europe.
I did buy a relatively cheap Tuya based powerstrip on Amazon and flashed it with Espurna firmware (which offers a nice REST API for switching the sockets on and off), using this tool https://github.com/ct-Open-Source/tuya-convert .
No soldering required, flashing works via OTA.

I also wrote a reef-pi driver to implement the Espurna API and can successfully use it as an outlet to control my pumps and heater. If you guys are interested i can submit a PR, but since it's my first GO code, some refactoring will be required.

**Comment by ranjib** [comment]
I am adding tplink hs1xx series smart plug support. We wont be able to support all major brands, from what I understand this brand is available in UK, US and Australia. Let me know what you think. I'll close this ticket for the time being. Feel free to open it if you think this is still not done. We'll have some UI work left (for configuration), but we can track that separately.
https://github.com/reef-pi/reef-pi/pull/785

**Comment by narkotix781** [comment]
> i started building this project but also rely on a smart plug since the ADJ powerstrip is not available in Europe.
> I did buy a relatively cheap Tuya based powerstrip on Amazon and flashed it with Espurna firmware (which offers a nice REST API for switching the sockets on and off), using this tool https://github.com/ct-Open-Source/tuya-convert .
> No soldering required, flashing works via OTA.
> 
> I also wrote a reef-pi driver to implement the Espurna API and can successfully use it as an outlet to control my pumps and heater. If you guys are interested i can submit a PR, but since it's my first GO code, some refactoring will be required.

Hi Philkry - I`m interested in that driver. Are you able to share it at all?

**Comment by philkry** [comment]
@narkotix781 sorry, but i ditched that implementation in the end since my smart plugs performed  random factory resets with Espurna firmware which made it quite unreliable for the intended use case.
i never found the time to properly debug if it was my implementation or Espurna itself. I went with the TPLink plugs in the end.
