### ISSUE TITLE
[Request] Mobile App

### ISSUE THREAD

**Issue by AymenRachid** [reef-pi/reef-pi#771]
**Is your feature request related to a problem? Please describe.**
Having to go through the computer and run the whole system each time you want to use this software is somehow annoying.

**Describe the solution you'd like**
I thought that creating a mobile app would help and can be easier, user-friendly and even more practical.

**Comment by ranjib** [comment]
this is a very cool idea. i would definitely love to contribute.. the current web ui is responsive. I dont have any plans for a mobile app due to time. I'll close this ticket as this repo is for the core backend and a minimal web ui that supports it. If theres enough interest we can create a repo for the mobile app under reef-pi namespace.

**Comment by zekth** [comment]
@ranjib the mobile app transition as we discuss will be PWA.
