### ISSUE TITLE
3.0 alpha 2 - Temperature graphs don't update w/ min/max values

### ISSUE THREAD

**Issue by dmolavi** [reef-pi/reef-pi#787]
In 3.0 alpha 2, I modified the temp graph min/max values, saved and restarted reef-pi. The graphs did not reflect the new values, however. 
![Screenshot from 2019-06-08 12-59-20](https://user-images.githubusercontent.com/89136/59153921-51fd5480-8a34-11e9-99c4-0064d2336a40.png)

**Comment by Ranthalion** [comment]
This is the existing behavior for charts.  The initial reading on the far left of the chart is 0, which is below your configured minimum.  As a result, the chart moves the minimum to be able to show that 0 value.  Once you've collected enough data points for the 0 to roll off, the min/max that you've configured will be reflected on chart (assuming all reading values fall within that range).

**Comment by dmolavi** [comment]
Huh...I don't recall it being like that in 2.2, but then I don't remember what I had for breakfast. This can be closed if this is expected.

**Comment by clownfish44** [comment]
Honestly, it should put a red dot on the chart where the error/ value not in the range is and then scale to how you have it set because its silly to have to wait 24 hours for data to fill before you can properly view the new correct numbers. This way you know it was either an error or something happened. It's silly for the first number to show 0 anyways.

**Comment by gminton86** [comment]
A quick fix for this is to set the check frequency really low. It will roll off fairly quickly, then change it back to the desired amount.
