### ISSUE TITLE
bug while setting ph calibration

### ISSUE THREAD

**Issue by mtorzews** [reef-pi/reef-pi#791]
I am having trouble calibrating my ph sensor. Specifically I can't create a cookie.txt file. 
This command "
curl -X POST -d '{"user":"pi", "password":"mike"}' -c cookie.txt http://192.168.1.161/auth/signin
"
runs and says "null"

Then I type ls -alh and I don't see a cookie.txt file. 

This worked on the first pi, but this time nada. Any suggestions?

well I fixed it. YAY

I re-entered my login info into reef-pi authentication tab. Rebooted and tried again. This time the cookie.txt file was created. I must have not been giving the right login and password to reef-pi as I didn't update them after installing reef-pi 3.0

Im glad it worked out. But I do think reef-pi has a bug , or unexpected behavior. Ideally it should respond with some kinda error message indicating a failed auth. Put otherway there should not be silent yet bad failures. I'll see if i can get time and fix it. It will be nice if you file a bug report. I wont forget that way

**Comment by Ranthalion** [comment]
I believe this may have been due to a bad username or password.  The auth/signin method does not return a response body, which is why you see null.  The response header would contain whether the request was successful. 

You can use -D headers.txt to write the received headers to a file to confirm if this is the case.  If the login is invalid, you'll see  HTTP/1.1 401 Unauthorized.  A good login would give you HTTP/1.1 200 OK

 curl -X POST -d '{"user":"reef-pi", "password":"bad"}' -c cookie.txt -D header.txt http://localhost/auth/signin

**Comment by ranjib** [comment]
@mtorzews if you use curl with -v option you'll see reef-pi is correctly printing the 401 unauthorized error code. the curl CLI will still pass as its a successful http transaction (which means the webserver is just fine)
