### ISSUE TITLE
Support for EC and/or ORP probe

### ISSUE THREAD

**Issue by gminton86** [reef-pi/reef-pi#906]
Would love to have an EC probe for salinity ORP would be a second option also

**Comment by Ranthalion** [comment]
Do you have a link to any EC probe modules?  

Roberto's pH module can be configured as ORP, so we have driver support.

**Comment by gminton86** [comment]
yea this one 

https://www.atlas-scientific.com/product_pages/circuits/ezo_ec.html

**Comment by ranjib** [comment]
We have deprioritize this deliberately, due to their high cost, less usefulness (compared to ATO, ph sensor) and high operational cost (calibration, proneness to other interference).
Thats said, ezo driver code should be able to read  orp and ec probe as it is, from my initial reading of the data sheet. User needs to do i2c mode change, calibration out of band.
